### PR TITLE
Upgrades to Tapestry 5.7.0-SNAPSHOT and bumps version to 2

### PR DESCRIPTION
**Pull request by thiagohp**

### CODE REVIEW

**Comment by derkoe** [comment]
As 5.7.0 is unreleased I've changed this to 5.6.1 and merged it - see #6.

BTW - @thiagohp would be great if you have a look at https://github.com/apache/tapestry-5/pull/28

**Comment by thiagohp** [comment]
Thank you very much, @derkoe ! 
I'll take a look at that pull request as soon as I can (which may not be very soon, I'm afraid).

**Comment by thiagohp** [comment]
Hello, @derkoe !
This pull request won't work with 5.6.1 because 5.7.0 moved many classes from one package to another, so I guess your project doesn't compile anymore. tapestry-jaxws already worked with 5.6.1.

**Comment by thiagohp** [comment]
Hi again!
Tapestry 5.7.0 is already present at the Maven central repository.

**Comment by derkoe** [comment]
@thiagohp can you try the new version before I release it? https://oss.sonatype.org/content/repositories/snapshots/com/porscheinformatik/tapestry/jaxws/tapestry-jaxws/3.0.0-SNAPSHOT/

**Pull request merged**
